### ISSUE TITLE
make test is failing

### ISSUE THREAD

**Issue by djlwilder** [projectcalico/confd#104]
make test
<cut...>
docker run --rm --net=host \
	-v /var/jenkins/workspace/Ci-test_master-ES754XMDKZXQMAJXABQQ6NPWTO7EQQYKCQ272X7DR576TLOED7FQ/confd/tests/:/tests/ \
	-v /var/jenkins/workspace/Ci-test_master-ES754XMDKZXQMAJXABQQ6NPWTO7EQQYKCQ272X7DR576TLOED7FQ/confd/bin:/calico/bin/ \
	-e RELEASE_BRANCH=master \
	-e LOCAL_USER_ID=0 \
	calico/go-build-ppc64le:latest /tests/test_suite_kdd.sh
Starting with UID : 0
adduser: uid '0' in use
Waiting for k8s API server to come on line
Populating k8s with test data that cannot be handled by calicoctl
customresourcedefinition "ippools.crd.projectcalico.org" configured
customresourcedefinition "bgppeers.crd.projectcalico.org" configured
customresourcedefinition "globalnetworkpolicies.crd.projectcalico.org" configured
customresourcedefinition "felixconfigurations.crd.projectcalico.org" configured
customresourcedefinition "bgpconfigurations.crd.projectcalico.org" configured
customresourcedefinition "clusterinformations.crd.projectcalico.org" configured
node "kube-master" created
node "kube-node-1" created
node "kube-node-2" created
Waiting for CRDs to be ready
Partial success: applied the first 4 out of 7 resources:
Hit error: operation Create is not supported on Node(kube-master)
Makefile:99: recipe for target 'test-kdd' failed
make: *** [test-kdd] Error 1

**Comment by caseydavenport** [comment]
@ozdanborne I believe this is likely your failure.
