### ISSUE TITLE
Full test coverage of templates for both KDD / etcd

### ISSUE THREAD

**Issue by tomdee** [projectcalico/confd#15]
How many tests would we need for complete path coverage through the template files?

**Comment by heschlie** [comment]
After talks with @robbrockbank and @tomdee we appear to have 10 cases to test:

- KDD/node-mesh/ipip-enabled
- KDD/node-mesh/ipip-disabled
- KDD/node-mesh/ipip-cross-subnet
- KDD/explicit-peering/global (unsupported for now)
- KDD/explicit-peering/node-specific (unsupported for now)
- etcd/node-mesh/ipip-enabled
- etcd/node-mesh/ipip-disabled
- etcd/node-mesh/ipip-cross-subnet
- etcd/explicit-peering/global
- etcd/explicit-peering/node-specific

The global and node-specific peering in KDD will be ready in the near future.

**Comment by heschlie** [comment]
All points covered in latest tests.
