### ISSUE TITLE
Will there be a 3.3.0 tag?

### ISSUE THREAD

**Issue by earlruby** [projectcalico/confd#166]
Will there be a 3.3.0 tag on this repo to match the Calico 3.3.0 release?

**Comment by caseydavenport** [comment]
@earlruby we've stopped cutting releases of this repository since it no longer produces any artifacts - the commit used in Calico v3.3.0  can be seen here: https://github.com/projectcalico/node/blob/v3.3.0/glide.lock#L110-L112
