### ISSUE TITLE
How to build confd with thie repo

### ISSUE THREAD

**Issue by lcnsir** [projectcalico/confd#27]
I have tried to build the confd with this repo, but errors found:
backends/k8s/client.go:16:2: cannot find package "k8s.io/client-go/pkg/api/errors" in any of:
	/usr/local/go/src/k8s.io/client-go/pkg/api/errors (from $GOROOT)
	/root/calico/calico/src/k8s.io/client-go/pkg/api/errors (from $GOPATH)
backends/k8s/client.go:14:2: cannot find package "k8s.io/client-go/pkg/apis/meta/v1" in any of:
	/usr/local/go/src/k8s.io/client-go/pkg/apis/meta/v1 (from $GOROOT)
	/root/calico/calico/src/k8s.io/client-go/pkg/apis/meta/v1 (from $GOPATH)
backends/k8s/client.go:10:2: cannot find package "k8s.io/client-go/pkg/runtime" in any of:
	/usr/local/go/src/k8s.io/client-go/pkg/runtime (from $GOROOT)
	/root/calico/calico/src/k8s.io/client-go/pkg/runtime (from $GOPATH)
backends/k8s/client.go:8:2: cannot find package "k8s.io/client-go/pkg/runtime/schema" in any of:
	/usr/local/go/src/k8s.io/client-go/pkg/runtime/schema (from $GOROOT)
	/root/calico/calico/src/k8s.io/client-go/pkg/runtime/schema (from $GOPATH)
backends/k8s/client.go:9:2: cannot find package "k8s.io/client-go/pkg/runtime/serializer" in any of:
	/usr/local/go/src/k8s.io/client-go/pkg/runtime/serializer (from $GOROOT)
	/root/calico/calico/src/k8s.io/client-go/pkg/runtime/serializer (from $GOPATH)

And when I get  the code from https://github.com/kelseyhightower/confd, it's ok to build it.

After compare with the two repos,  a lot of code is different,  Is the confd in calico node from this repo?,  how we can build confd with this repo?

**Comment by heschlie** [comment]
Hi @lcnsir the README is not accurate for this repo, I'll get a fix up for it today.  To answer your question though, you should be able to execute `make all` to build and test, or `make vendor && make bin/confd` to just build confd from this repo.
