### ISSUE TITLE
Keep next hop in BGP advertisement.

### ISSUE THREAD

**Issue by tabka** [projectcalico/confd#308]
Hello,

After [this request](https://github.com/projectcalico/confd/pull/257#issuecomment-571279379) I'm opening a new issue.

we are running Project Calico 3.8.1 as SDN for our on-premise k8s clusters. Our network looks as follows:

We host worker nodes in different edge zones (fire compartments). The edge zones are interconnected by an L3VPN.
All worker nodes run a single calico-node pod which is deployed as a daemon set.
We have two calico-node pods per edge zone which are configured to serve as route reflectors (RRs).
Each RR maintains an eBGP session with the EoR switch in the same edge zone.
All EoR switches and the distribution switch peer with each other in the L3VPN (iBGP full mesh).
All RRs are peering with each other in the same edge zones as iBGP full mesh. Each calico-node peers with all RRs in the same edge zone (iBGP).
Our ToR switches are plain L2 switches, so we are not able to use them as RRs inline to the traffic path.
Because we are using eBGP between the RRs and the EoR switches, the default behavior looks like "next hop self" is set.
In this case traffic from the EoRs towards the workloads inside an edge zone would be routed through the route reflectors.
Instead, we want the traffic to be routed directly towards the worker nodes.
That's why we set the option "next hop keep" in the bird configuration and deployed a custom calico-node image.

Would it be possible to have this option configurable e.g. via an environment variable?
Would it be possible to configure "next hop keep" as a default for each and every calico-node, because in our opinion it never makes sense to route the traffic through a calico-node configured as RR?

![next_hop](https://user-images.githubusercontent.com/7596551/72158090-b7923480-33b9-11ea-8d8c-8f5dac0b011e.png)

**Comment by rafaelvanoni** [comment]
@neiljerram Could you please take a look at this one?

**Comment by caseydavenport** [comment]
> Would it be possible to configure "next hop keep" as a default for each and every calico-node, because in our opinion it never makes sense to route the traffic through a calico-node configured as RR?

I don't think we can do this for all nodes, but maybe it makes sense for RRs? Need to think about this more. We might also be able to enhance the BGPPeer resource to allow configuration of next-hop keep on a per-peer basis.

**Comment by tabka** [comment]
Yes what we really need is to add it to the RRs only ! We only said for every calico-node for the sake of simplicity. Any way it would be super nice to have this.

**Comment by caseydavenport** [comment]
This should be addressed by a configuration option in this PR: https://github.com/projectcalico/libcalico-go/pull/1266
