### ISSUE TITLE
Make test hangs somtimes.

### ISSUE THREAD

**Issue by djlwilder** [projectcalico/confd#36]
Make test can hang sometimes after printing "Waiting for CRDs to apply". nThe failure is interment maybe one out of five times I run make test it hangs.

**Comment by djlwilder** [comment]
I think I see the problem, in tests/utils.sh:populate_kdd() I removed all the output redirection on the kubectl commands so I could see the errors.  I found that the first "kubectl apply" is failing because the hyperkube apiserver is not fully ready.  If I retry the command it works ok.

The script is using "kubectl version" in a loop to test if the server is available,  but it looks like this may not be sufficient to verify the server it fully up.  I am going to try moving the retry loop to the first "kubectl apply" command and see if it helps.

**Comment by caseydavenport** [comment]
Fixed by https://github.com/projectcalico/confd/pull/37, thanks!
