### ISSUE TITLE
make test is failing

### ISSUE THREAD

**Issue by djlwilder** [projectcalico/confd#41]
make test started failing today.  Here is the failure.
```<cut>
Files /tests/compiled_templates/mesh/ipip-cross-subnet/bird_ipam.cfg and /etc/calico/confd/config/bird_ipam.cfg differ
bird_ipam.cfg templates do not match, showing diff of expected vs received
--- /tests/compiled_templates/mesh/ipip-cross-subnet/bird_ipam.cfg
+++ /etc/calico/confd/config/bird_ipam.cfg
@@ -15,7 +15,7 @@
 
   if ( net ~ 192.168.0.0/16 ) then {
 
-    if ( from ~ 10.192.0.0/16 ) then
+    if ( bgp_next_hop ~ 10.192.0.0/16 ) then
       krt_tunnel = "";                     
     else
       krt_tunnel = "tunl0";       
<cut>```

**Comment by djlwilder** [comment]
The problem looks to be caused by the last commit on calico.git that updated calico_node/filesystem/etc/calico/confd/templates/bird_ipam.cfg.template

I updated test/utils.sh:get_templates()  to grab  bird_ipam.cfg.template just before the last commit and the test ran clean.

--- tests/utils.sh	2017-09-29 16:38:59.450816846 -0700
+++ tests/utils.sh.hack	2017-09-29 16:31:07.491406743 -0700
@@ -74,6 +74,9 @@
     if [ ! -d ${repo_dir} ]; then
         echo "Getting latest confd templates from calico repo"
         git clone https://github.com/projectcalico/calico.git ${repo_dir}
+	pushd ${repo_dir}
+	git checkout 659fbada3687becefae1e5702be02251fb2398f2
+	popd 
         ln -s ${repo_dir}/calico_node/filesystem/etc/calico/ /etc/calico
     fi
 }

**Comment by caseydavenport** [comment]
Thanks for raising.

That test is wrong now - we've changed to using the BGP next hop so that cross-subnet mode works with route reflectors.

I've opened https://github.com/projectcalico/confd/pull/42 to fix the test.
